### ISSUE TITLE
Missing README on npmjs.com

### ISSUE THREAD

**Issue by tsteenbe** [heremaps/harp-font-resources#25]
See "Unable to find a readme for @here/harp-font-resources@0.2.2" on https://www.npmjs.com/package/@here/harp-font-resources

**Comment by haraldF** [comment]
That should be fixed as soon as this repository goes public

**Comment by musculman** [comment]
This is because the package was published with local changes that were not published to github and the SHA1 of the published npm package does not match the one in github. I just checked by downloading it. We should publish 0.2.3 to fix it. And then point harp.gl to it.

**Comment by musculman** [comment]
Now that the PR is merged, the vulnerabilities are gone. We just need to release to npmjs the new version.

**Comment by musculman** [comment]
New package 0.2.3 is published but the README is still not visible :/

**Comment by musculman** [comment]
Do we need perhaps to put a "files" section in the package.json and list README.md there? I thought it should be picked up automatically but maybe that helps.

**Comment by zbigg** [comment]
IDK, but this line in `package.json` seems fishy:
```
"url": "git://github.com:heremaps/harp-font-resources.git"
```
This doesn't even work because `heremaps` is intepreted as port.
Shouldn't it be:

"url": "git://github.com/heremaps/harp-font-resources.git"

**Comment by musculman** [comment]
I think you found it! I have reviewed these files multiple times but my eyes always overlooked it. I will fix it, thanks!!

**Comment by zbigg** [comment]
Now i found that all the `harp.gl` `package.json`s have same issue too ...
```
$ grep github.com: mapsdk/coresdk/@here/*/package.json
mapsdk/coresdk/@here/generator-harp.gl/package.json:        "url": "git://github.com:heremaps/harp.gl.git"
mapsdk/coresdk/@here/harp-datasource-protocol/package.json:        "url": "git://github.com:heremaps/harp.gl.git"
mapsdk/coresdk/@here/harp-debug-datasource/package.json:        "url": "git://github.com:heremaps/harp.gl.git"
mapsdk/coresdk/@here/harp-examples/package.json:        "url": "git://github.com:heremaps/harp.gl.git"
```
I'll fix it there too ...

**Comment by musculman** [comment]
Wait, after second thought, this cannot be the case because if I see @here/harp-geoutils package.json file here: https://github.com/heremaps/harp.gl/blob/master/%40here/harp-geoutils/package.json and the npm information here: https://www.npmjs.com/package/@here/harp-geoutils
After reading about it, it looks like it is also a valid way of defining the github urls, meaning that both `github.com/` and `github.com:` work.

**Comment by musculman** [comment]
I am closing the issue for the same reasons exposed in https://github.com/heremaps/harp.gl/pull/457

Ref: https://npm.community/search?q=Unable%20to%20find%20a%20readme%20for
